import '@prezly/content-renderer-react-js/styles.css';
import '@prezly/uploadcare-image/build/styles.css';
import '../styles/styles.globals.scss';
import { Layout } from '@/components/Layout';

/* Tailwind CSS Reset is messing up with UI components styling, so these styles should come after Tailwind */
import '@prezly/themes-ui-components/styles.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="h-full antialiased" suppressHydrationWarning>
            <body className="flex h-full bg-zinc-50 dark:bg-black">
                {/* <Providers> */}
                <div className="flex w-full">
                    <Layout>{children}</Layout>
                </div>
                {/* </Providers> */}
            </body>
        </html>
    );
}
